uploads = []
generated = []

[[outputs]]
id = "lIcEzOdnqzzsuX84mN9mW"
uri = "file://premium_tools_combined_fixed.zip"
type = "unspecified"
title = "premium_tools_v5 — Real Comment + Auto React + Web UI"

[[outputs]]
id = "g0mihR_5gaNBdoT7-HrjC"
uri = "file://premium_tools_v6.zip"
type = "unspecified"
title = "Vern Premium Tools v6 — Complete Suite"

[[outputs]]
id = "raCpqy2LgW7ZrDoRaaCDY"
uri = "file://premium_tools_v8.zip"
type = "unspecified"
title = "VERN PREMIUM TOOLS v8 — Lara APK Edition"
